name: Pipeline de Planilla de Pagos

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Ejecutar pruebas simulando entorno global
      run: node --experimental-test-module-mocks --test planilla.test.js
